version: '3.1'

services:
  jupyter:
    build: '.'
    restart: always
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: 'yes'
    volumes:
      - ./notebooks:/home/jovyan/work

